config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'


  # get '/auth/:provider/callback', to: 'sessions#create'
  # get '/logout', to: 'sessions#destroy'


  #get 'users/matching/', to: 'users#matching', param: :id

  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    #get :matching, to: 'users#matching'
   member do
     get :following, :followers
     get :matching
   end
 end

  resources :dreams, only: [:new, :create, :edit, :index, :show, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :dream_comments, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/dream.rb
class Dream < ApplicationRecord

	validates :title, presence: true
	validates :body, presence: true

	belongs_to :user
	attachment :image

	has_many :dream_comments, dependent: :destroy

	has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end

        def self.search(search)
        	if search
        		Dream.where(['title LIKE ?', "%#{search}%"])
        	else
        		Dream.all
        	end
        end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController


	def new
		@dream = Dream.new
	end

	def create
		@dream = current_user.dreams.build(dream_params)
		if @dream.save
			redirect_to dream_path(@dream)
		else
			render "new"
		end
	end

	def index
		@dreams = Dream.all
		@dreams = Dream.search(params[:search])
	end

	def show
		@dream = Dream.find(params[:id])
		@dream_comments = @dream.dream_comments
		@dream_comment = DreamComment.new
	end

	def edit
		@dream = Dream.find(params[:id])
	end

	def update
		@dream = Dream.find(params[:id])
		if @dream.update(dream_params)
			redirect_to dream_path
		else
			render "edit"
		end
	end

	def destroy
		dream = Dream.find(params[:id])
		dream.destroy
		redirect_to dreams_path(dream.user)
	end

	def search
		@dreams = Dream.search(params[:search])
		render "index"
	end

	private

	def dream_params
		params.require(:dream).permit(:title, :body, :image)
	end
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/edit.html.erb
<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">Dream Edit</h4>
	</div>
	<div class="edit-container" style="width:65%; margin: 20px auto;">
		<%= form_for @dream do |f| %>
		<div class="text-right">
			<%= link_to "削除する",dream_path(@dream), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger destroy_dream_#{@dream.id}" %>
		</div>
		<div class="field">
			<%= f.label :TITLE %>
			<%= f.text_field :title, class: "input" %>
		</div>

		<div class="field">
			<%= f.label :INTRODUCTION %>
			<%= f.text_area :body, class: "textarea" %>
		</div>

		<div class="field">
			<%= f.label :PICTURE %>
			<%= f.attachment_field :image, class: "input" %>
		</div>

		<div class="text-left">
			<%= f.submit '投稿', class: "btn btn-success" %>
		</div>
	</div>
	<% end %>
</div>

app/views/dreams/index.html.erb
<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">Dream List</h4>
	</div>
	<div class="row" style="width: 100%;">
		<div class="search">
			<%= form_tag(search_dreams_path,:method => 'get') do %>
			<%= text_field_tag :search %>
			<%= submit_tag '検索', :title => nil %>
			<% end %>
		</div>
		<ul class="list">
			<% @dreams.reverse.each do |dream| %>
			<li>
				<div class="img">
					<figure>
						<% if dream.user.image %>
						<img src="<%= dream.user.image %>" style= "width:200px; height:200px; margin-left: 20px;">
						<% else %>
						<%= attachment_image_tag dream.user, :profile_image, fallback: "no_image.jpg", style:"width:200px; height:200px; margin-left: 20px; "%>
					</figure>
					<% end %>
				</div>
				<div class="text">
					<p class="date"><%= dream.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
					<div class="dream-title"><%= link_to dream.title, dream_path(dream.id) %></div>
					<p class="name">投稿者　<%= link_to dream.user.name, user_path(dream.user) %></p>
				</div>
			</li>
			<% end %>
		</ul>
	</div>
</div>
<%= render "layouts/pagetop" %>

app/views/dreams/new.html.erb
<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">Dream Post</h4>
	</div>

	<div class="new-container" style="width:65%; margin: 20px auto;">
		<%= form_for @dream do |f| %>
		<div class="field">
			<%= f.label :TITLE %>
			<%= f.text_field :title, class: "input" %>
		</div>

		<div class="field">
			<%= f.label :INTRODUCTION %>
			<%= f.text_area :body, class: "textarea" %>
		</div>

		<div class="field">
			<%= f.label :PICTURE %>
			<%= f.attachment_field :image, class: "input" %>
		</div>

		<%= f.submit '投稿', class: "btn btn-success" %>
		<% end %>
	</div>
</div>

app/views/dreams/show.html.erb
<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">Dream Details</h4>
	</div>
</div>
<div class="show-container" style="width:45%; margin: 20px auto;">
	<%= attachment_image_tag @dream, :image, fallback: "no_image.jpg", style:"width:30%; height:30%; margin-left:35%; margin-bottom: 20px;" %>
	<table class="table is-narrow">
		<tr>
			<th>Title</th>
			<td><%= simple_format @dream.title %></td>
		</tr>
	</table>
	<table class="table is-narrow">
		<tr>
			<th>Introduction</th>
			<td><%= simple_format @dream.body %></td>
		</tr>
	</table>
	<% if @dream.user == current_user %>
	<%= link_to "編集する", edit_dream_path(@dream), class: "btn btn-primary" %>
	<% end %>
	<div class="text-right" style="margin-right: 20%;">
		<% if @dream.favorited_by?(current_user) %>
		<%= link_to dream_favorites_path(@dream), method: :delete do %>
		<i class="fa fa-heart" aria-hidden="true" style="color: darkorange;"></i>
		<%= @dream.favorites.count %> いいね
		<% end %>
		<% else %>
		<%= link_to dream_favorites_path(@dream), method: :post do %>
		<i class="fa fa-heart-o" aria-hidden="true"></i>
		<%= @dream.favorites.count %> いいね
		<% end %>
		<% end %>
	</div>
</div>
<div class="container" style="width:50%; margin: 20px auto;">
	<h2>コメントする</h2>
	<%= form_for [@dream, @dream_comment] do |f| %>
	<%= f.text_area :comment, rows:'5', class: "form-control" %>
	<%= f.submit "送信", class: "btn btn-primary pull-right" %>
	<% end %>
</div>
<div class="container" style="width:70%; margin: 20px auto;">
	<h2 class="comment">コメント一覧</h2>
	<% @dream.dream_comments.reverse.each do |dream_comment| %>
	<table class="table">
		<thead>
			<tr>
				<th><%= link_to dream_comment.user.name, "/users/#{dream_comment.user_id}" %></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= dream_comment.created_at.strftime('%Y/%m/%d') %></td>
				<td><%= dream_comment.comment %></td>
				<td><% if dream_comment.user == current_user %>
					<%= link_to "Destroy",dream_dream_comments_path(@dream.id,dream_comment.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger pull-right destroy_dream_comment#{@dream.id}" %></td>
			<% end %>
			</tr>
		</tbody>
		<% end %>
	</table>
</div>
<%= render "layouts/pagetop" %>