config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'


  # get '/auth/:provider/callback', to: 'sessions#create'
  # get '/logout', to: 'sessions#destroy'


  #get 'users/matching/', to: 'users#matching', param: :id

  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    #get :matching, to: 'users#matching'
   member do
     get :following, :followers
     get :matching
   end
 end

  resources :dreams, only: [:new, :create, :edit, :index, :show, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :dream_comments, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable

  attachment :profile_image

  has_many :dreams, dependent: :destroy
  has_many :dream_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :email, presence: true
  validates :name, presence: true

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

   def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        image: auth.info.image,
        name: auth.info.name,
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		puts current_user
		@user = User.find(params[:id])
		@dream = Dream.all
		followerIdList = Relationship.select(:user_id).where(follow_id: current_user.id)
		matchUserIdList = Relationship.select(:follow_id).where(user_id: current_user.id, follow_id: followerIdList)
		matchUserList = User.where(id: matchUserIdList)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "successfully updated user!"
			redirect_to user_path(@user)
		else
			render "edit"
		end
	end

	def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def matching
	followerIdList = Relationship.select(:user_id).where(follow_id: params[:id])
	matchUserIdList = Relationship.select(:follow_id).where(user_id: params[:id], follow_id: followerIdList)
	@matchUserList = User.where(id: matchUserIdList)
	render 'show_matching'
  end



private

def user_params
	params.require(:user).permit(:name, :email, :profile, :profile_image)
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">User Edit</h4>
	</div>
</div>

<div class="container">
	<div class="edit-container" style="width:65%; margin: 20px auto;">
		<%= form_for @user do |f| %>
		<div class="form-group">
			<%= f.label :name, "ユーザー名" %>
			<div class="row">
				<%= f.text_field :name, class: "input col-md-4" %>
			</div>
		</div>

		<div class="field">
			<%= f.label :profile, "プロフィール" %>
			<div class="row">
				<%= f.text_area :profile, class: "textarea" %>
			</div>
		</div>

		<div class="form-group">
			<%= f.label :email, "メールアドレス" %>
			<div class="row">
				<%= f.email_field :email, class: "input" %>
			</div>
		</div>

		<div class="field">
			<%= f.label :profile_image, "プロフィール画像" %>
			<div class="row">
				<%= f.attachment_field :profile_image, class: "input" %>
			</div>
		</div>

		<%= f.submit "更新", class: "button is-success" %>
		<% end %>
	</div>
</div>
</div>

app/views/users/index.html.erb
<style>
th {
	background: #FFFFBB;
}
</style>

<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">User一覧</h4>
	</div>
</div>
<div class="show-container" style="width:40%; margin: 20px auto;">
	<table class="table">
		<% @users.each do |user| %>
		<thead>
			<tr>
				<th>
					<% if user.image %>
						<img src="<%= user.image %>" style= "width:100px; height:100px;">
					<% else %>
						<%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", style:"width:100px; height:100px; " %>
					<% end %>
				</th>
				<th>
					<% unless current_user == user %>
						<% if current_user.following?(user) %>
							<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
								<%= hidden_field_tag :follow_id, user.id %>
								<%= f.submit 'フォロー中', class: 'btn-gradient-flat' %>
							<% end %>
						<% else %>
							<%= form_for(current_user.relationships.build) do |f| %>
								<%= hidden_field_tag :follow_id, user.id %>
								<%= f.submit 'フォローする', class: "btn-flat-simple " %>
							<% end %>
						<% end %>
					<% end %>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><strong><%= link_to user.name, user_path(user) %></strong></td>
			</tr>
			<tr>
				<td><%= user.profile %></td>
			</tr>
		</tbody>
		<% end %>
	</table>
</div>
<%= render "layouts/pagetop" %>

app/views/users/show.html.erb
<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">My Page</h4>
	</div>
</div>
<div class="show-container" style="width:40%; margin: 20px auto; ">
	<table class="table">
		<div class="mypage">
			<thead>
				<tr>
					<th>
						<% if @user.image %>
						<img src="<%= @user.image %>" style= "width:100px; height:100px;">
						<% else %>
						<%= attachment_image_tag @user, :profile_image,  size: "120x120", fallback: "no_image.jpg", class: "profile_image is-rounded" %>
						<% end %>
					</th>
					<th>
						<% unless current_user == @user %>
						<% if current_user.following?(@user) %>
						<%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f| %>
						<%= hidden_field_tag :follow_id, @user.id %>
						<%= f.submit 'フォロー中', class: "btn-gradient-flat" %>
						<% end %>
						<% else %>
						<%= form_for(current_user.relationships.build) do |f| %>
						<%= hidden_field_tag :follow_id, @user.id %>
						<%= f.submit 'フォローする', class: "btn-flat-simple" %>
						<% end %>
						<% end %>
						<% end %>
					</th>
					<th>
						<% if @user.id == current_user.id %>
						<%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
						<% end %>
					</th>
				</tr>
			</thead>
		</div>
			<tbody>
				<tr>
					<td><strong><%= @user.name %></strong></td>
				</tr>
				<tr>
					<td><%= @user.profile %></td>
				</tr>
				<tr><% @user ||= current_user %>
					<td><strong id="following" class="stat">
						<%= @user.followings.count %>
					</strong>
					<a><%= link_to "フォロー", following_user_path(@user) %></a>
					<strong id="followers" class="stat">
						<%= @user.followers.count %>
					</strong>
					<a><%= link_to "フォロワー", followers_user_path(@user) %>
					</a>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="text-left">
   		<h2><%= link_to "Mathing Users☆", matching_user_path(@user) %></h2>
	</div>
</div>
<div class="container" style="width:68%; margin: 20px auto; padding-top: 80px;">
	<div class="text-center">
		<h2 style="border-bottom: 2px solid #FF4F02;"> My Post</h2>
		<% @user.dreams.reverse.each do |dream| %>
		<table class="table table-striped">
			<thead>
				<tr>
					<th><%= dream.updated_at.strftime("%Y-%m-%d %H:%M") %></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><%= link_to dream.title, dream_path(dream) %></td>
				</tr>
			</tbody>
		</table>
		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
<style>
 tr {
 	background: #FFFFBB;
 }
</style>

<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">フォロー中</h4>
	</div>
</div>
<div class="show-container" style="width:40%; margin: 20px auto;">
	<% @user.followings.each do |user| %>
<table class="table">
	<thead>
		<tr>
			<th><%= attachment_image_tag user, :profile_image, :fill, 90, 90, fallback: "no_image.jpg" %></th>
		</tr>
	</thead>
			<tbody>
				<tr>
					<td><strong><%= link_to user.name, user_path(user) %></strong></td>
				</tr>
				<tr>
					<td><%= user.profile %></td>
				</tr>
	</tbody>
</table>
<% end %>
</div>

app/views/users/show_follower.html.erb
<style>
 tr {
 	background: #FFFFBB;
 }
</style>

<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">フォロワー</h4>
	</div>
</div>
<div class="show-container" style="width:40%; margin: 20px auto;">
	<% @user.followers.each do |user| %>
	<table class="table">
	<thead>
		<tr>
			<th><%= attachment_image_tag user, :profile_image, :fill, 90, 90, fallback: "no_image.jpg" %></th>
		</tr>
	</thead>
			<tbody>
				<tr>
					<td><strong><%= link_to user.name, user_path(user) %></strong></td>
				</tr>
				<tr>
					<td><%= user.profile %></td>
				</tr>
	</tbody>
</table>
<% end %>
</div>

app/views/users/show_matching.html.erb
<style>
 tr {
 	background: #FFFFBB;
 }
</style>

<div class="container">
	<div class="row" style="width: 100%; margin: 50px auto;">
		<h4 style="margin-bottom: 20px; border-left: 2px solid #FF4F02; padding: 10px;">マッチング中</h4>
	</div>
</div>
<div class="show-container" style="width:40%; margin: 20px auto;">
	<% @matchUserList.each do |user| %>
<table class="table">
	<thead>
		<tr>
			<th><%= attachment_image_tag user, :profile_image, :fill, 90, 90, fallback: "no_image.jpg" %></th>
		</tr>
	</thead>
			<tbody>
				<tr>
					<td><strong><%= link_to user.name, user_path(user) %></strong></td>
				</tr>
				<tr>
					<td><%= user.profile %></td>
				</tr>
	</tbody>
</table>
<% end %>
</div>