config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'


  # get '/auth/:provider/callback', to: 'sessions#create'
  # get '/logout', to: 'sessions#destroy'


  #get 'users/matching/', to: 'users#matching', param: :id

  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    #get :matching, to: 'users#matching'
   member do
     get :following, :followers
     get :matching
   end
 end

  resources :dreams, only: [:new, :create, :edit, :index, :show, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :dream_comments, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dream.rb
class Dream < ApplicationRecord

	validates :title, presence: true
	validates :body, presence: true

	belongs_to :user
	attachment :image

	has_many :dream_comments, dependent: :destroy

	has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end

        def self.search(search)
        	if search
        		Dream.where(['title LIKE ?', "%#{search}%"])
        	else
        		Dream.all
        	end
        end
end

app/models/dream_comment.rb
class DreamComment < ApplicationRecord

	belongs_to :user

    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :dream
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable

  attachment :profile_image

  has_many :dreams, dependent: :destroy
  has_many :dream_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :email, presence: true
  validates :name, presence: true

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

   def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        image: auth.info.image,
        name: auth.info.name,
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController


	def new
		@dream = Dream.new
	end

	def create
		@dream = current_user.dreams.build(dream_params)
		if @dream.save
			redirect_to dream_path(@dream)
		else
			render "new"
		end
	end

	def index
		@dreams = Dream.all
		@dreams = Dream.search(params[:search])
	end

	def show
		@dream = Dream.find(params[:id])
		@dream_comments = @dream.dream_comments
		@dream_comment = DreamComment.new
	end

	def edit
		@dream = Dream.find(params[:id])
	end

	def update
		@dream = Dream.find(params[:id])
		if @dream.update(dream_params)
			redirect_to dream_path
		else
			render "edit"
		end
	end

	def destroy
		dream = Dream.find(params[:id])
		dream.destroy
		redirect_to dreams_path(dream.user)
	end

	def search
		@dreams = Dream.search(params[:search])
		render "index"
	end

	private

	def dream_params
		params.require(:dream).permit(:title, :body, :image)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		dream = Dream.find(params[:dream_id])
		favorite = current_user.favorites.new(dream_id: dream.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		dream = Dream.find(params[:dream_id])
		favorite = current_user.favorites.find_by(dream_id: dream.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
		
	end
end

app/controllers/sessions_controller.rb
# #class SessionsController < ApplicationController

# 	#def create
# 		unless request.env['omniauth.auth'][:uid]
# 			flash[:danger] = '連携に失敗しました'
# 			redirect_to root_url
# 		end
# 		user_data = request.env['omniauth.auth']
# 		user = User.find_by(uid: user_data[:uid])
# 		if user
# 			log_in user
# 			flash[:success] = 'ログインしました'
# 			redirect_to root_url
# 		else
# 			new_user = User.new(uid: user_data[:uid], nickname: user_data[:info][:nickname], name: user_data[:info][:name], image: user_data[:info][:image],)
# 			if new_user.save
# 				log_in new_user
# 				flash[:success] = 'ユーザー登録成功'
# 			else
# 				flash[:danger] = '予期せぬエラーが発生しました'
# 			end
# 			redirect_to root_url
# 		end
# 	end

# 	def destroy
# 		log_out if logged_in?
# 		flash[:success] = 'ログアウトしました'
# 		redirect_to root_url
# 	end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		puts current_user
		@user = User.find(params[:id])
		@dream = Dream.all
		followerIdList = Relationship.select(:user_id).where(follow_id: current_user.id)
		matchUserIdList = Relationship.select(:follow_id).where(user_id: current_user.id, follow_id: followerIdList)
		matchUserList = User.where(id: matchUserIdList)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "successfully updated user!"
			redirect_to user_path(@user)
		else
			render "edit"
		end
	end

	def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def matching
	followerIdList = Relationship.select(:user_id).where(follow_id: params[:id])
	matchUserIdList = Relationship.select(:follow_id).where(user_id: params[:id], follow_id: followerIdList)
	@matchUserList = User.where(id: matchUserIdList)
	render 'show_matching'
  end



private

def user_params
	params.require(:user).permit(:name, :email, :profile, :profile_image)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dream_comment_helper.rb
module DreamCommentHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# 	def log_in(user)
# 		session[:uid] = user.uid
# 	end

# 	def current_user
# 		if session[:uid]
# 			@current_user ||= User.find_by(uid: session[:uid])
# 		end
# 	end

# 	def logged_in?
# 		!current_user.nil?
# 	end

# 	def log_out
# 		session.delete(:uid)
# 		@current_user = nil
# 	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<p class="footer-text">©︎2020 by hirokazu</p>
</footer>

app/views/layouts/_pagetop.html.erb
<span id="back">
	<a href="#">
		<%= image_tag 'button.png' %>
	</a>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dream</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Corben:700 rel="stylesheet">
</head>


<body>
  <nav class="navbar is-warning">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navber-item" do %>
    <h1 class="maintatle">D-Connect</h1>
    <% end %>
    <div class="navbar-burger buger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <% if user_signed_in? %>
  <div class="navbar-menu">
    <div class="navbar-item">
      <%= link_to 'Dream', dreams_path, class: "navbar-item buttun is-warning is-light" %>
    </div>
    <div class="navbar-item">
      <%= link_to 'Dream Post', new_dream_path, class: "navbar-item buttun is-warning is-light" %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to 'User', users_path, class: "navbar-item buttun is-warning is-light" %></p>
            <p class="control">
              <%= link_to 'My Page', user_path(current_user.id), class: "navbar-item buttun is-warning is-light" %></p>
              <p class="control">
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "navbar-item buttun is-warning is-light" %></p>
              </div>
            </div>
          </div>
          <% else %>
          <div id="navbarExampleTransparentExample" class="navbar-menu">
            <div class="navbar-end">
              <div class="navbar-item">
                <div class="field is-grouped">
                  <p class="control">
                    <%= link_to 'Log In', new_user_session_path, class: "navbar-item buttun is-warning is-light" %></p>
                    <p class="control">
                      <%= link_to 'Sign Up', new_user_registration_path, class: "navbar-item buttun is-warning is-light" %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          </nav>
        <%= yield %>
        <%= render "layouts/footer" %>
      </body>
 </html>